### ISSUE TITLE
Repeating code blocks

### ISSUE THREAD

**Issue by Sup3Legacy** [Lioness100/guess-that-lang#15]
When playing the game, I often encounter repeated code blocks, especially **a lot** of Javascript, e.g. a `startgame` function I get at least once per game, sometimes twice in a row. Is this intended?

Edit: I did input my GH token

**Comment by Lioness100** [comment]
I've also encountered this problem a bunch, ~8 hours ago I ran into the exact same `startGame` function a few times in a row too. My only theory right now is just unluckiness, but it could possibly be a bug. When the CLI gets code to show, it:

1. Gets 100 gists from a random page (0-100 because that's the amount of pages of gists GitHub will display publicly) of the GitHub public gist API
2. Gets a random gist from this vec every round, replenishing it if all 100 have already been used (unlikely)

A few things we could do is research another gist API that doesn't have the 100 page limit, or using the github repository API, which would provide near limitless amounts of code, except it would take twice the API calls. You can see an example of this here: https://github.com/ModProg/language-guesser

**Comment by Lioness100** [comment]
Fixed by making the game fetch code from repos by default in https://github.com/Lioness100/guess-that-lang/commit/93fe9ac52743c24f3981f1adfc5c52c4dfcbcb5b
